<?php
declare(strict_types=1);
namespace jasonwynn10\StaffTools;

use pocketmine\plugin\PluginBase;

class Main extends PluginBase {
	public function onLoad() {
		parent::onLoad(); // TODO: Change the autogenerated stub
	}
	public function onEnable() {
		parent::onEnable(); // TODO: Change the autogenerated stub
	}
}